  /// \file RunControlInterface.cc
/*
 *
 * RunControlInterface.cc source template automatically generated by a class generator
 * Creation date : mar. janv. 24 2017
 *
 * This file is part of DQM4HEP libraries.
 *
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Remi ete
 * @copyright CNRS , IPNL
 */


#include "dqm4hep/RunControlInterface.h"

namespace dqm4hep {

  namespace core {

    RunControlInterface::RunControlInterface() :
      m_pRunControl(nullptr)
    {
      /* nop */
    }

    //-------------------------------------------------------------------------------------------------

    RunControlInterface::~RunControlInterface()
    {
      /* nop */
    }

    //-------------------------------------------------------------------------------------------------

    void RunControlInterface::startNewRun(const Run &run, const std::string &password)
    {
      if(nullptr != m_pRunControl)
        m_pRunControl->startNewRun(run, password);
    }

    //-------------------------------------------------------------------------------------------------

    void RunControlInterface::endCurrentRun(const std::string &password)
    {
      if(nullptr != m_pRunControl)
        m_pRunControl->endCurrentRun(password);
    }

    //-------------------------------------------------------------------------------------------------

    void RunControlInterface::setRunControl(refactor::RunControl *pRunControl)
    {
      m_pRunControl = pRunControl;
    }

  }

}
