  /// \file OnlineElement.h
/*
 *
 * OnlineElement.h header template automatically generated by a class generator
 * Creation date : lun. avr. 30 2018
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright 
 */


#ifndef DQM4HEP_ONLINEELEMENT_H
#define DQM4HEP_ONLINEELEMENT_H

#include <dqm4hep/MonitorElement.h>

namespace dqm4hep {
  
  namespace online {

    class ModuleApi;
    class OnlineElement;
    typedef std::shared_ptr<OnlineElement> OnlineElementPtr;
    typedef std::vector<OnlineElementPtr> OnlineElementPtrList;

    /** 
     *  @brief  OnlineElement class
     */ 
    class OnlineElement : public core::MonitorElement {
      friend class ModuleApi;
    public:
      /** 
       *  @brief  Make a shared pointer of OnlineElement
       */
      static OnlineElementPtr make_shared();

      /** 
       *  @brief  Make a shared pointer of OnlineElement
       *
       *  @param  pMonitorObject a valid ROOT object
       */
      static OnlineElementPtr make_shared(TObject *pMonitorObject);

      /** 
       *  @brief  Make a shared pointer of OnlineElement
       *
       *  @param  pMonitorObject a valid ROOT object
       *  @param  pReferenceObject a valid ROOT object as reference
       */
      static OnlineElementPtr make_shared(TObject *pMonitorObject, TObject *pReferenceObject);

      /** 
       *  @brief  Make a shared pointer of OnlineElement
       *
       *  @param  monitorObject a valid ROOT object pointer
       */
      static OnlineElementPtr make_shared(const core::PtrHandler<TObject> &monitorObject);

      /**
       *  @brief  Make a shared pointer of OnlineElement
       *
       *  @param  monitorObject a valid ROOT object pointer 
       *  @param  referenceObject a valid ROOT object pointer as reference
       */
      static OnlineElementPtr make_shared(const core::PtrHandler<TObject> &monitorObject,
                                                 const core::PtrHandler<TObject> &referenceObject);

      /**
       *  @brief  Destructor 
       */
      virtual ~OnlineElement() {}
      
      /**
       *  @brief  Set the run number
       * 
       *  @param runNum the run number
       */
      void setRunNumber(int runNum);
      
      /**
       *  @brief  Get the run number
       */
      int runNumber() const;
        
      /**
       *  @brief  Get the collector name.
       *          This property is set only if the element was collected
       */
      const std::string &collectorName() const;
      
      /**
       *  @brief  Get the module name that have booked this element
       */
      const std::string &moduleName() const;
      
      /**
       *  @brief  Set the description
       * 
       *  @param  desc the element description
       */
      void setDescription(const std::string &desc);
      
      /**
       *  @brief  Get the description
       */
      const std::string &description() const;
      
      /**
       *  @brief  Reset the monitor element
       *
       *  @param  resetQtests whether to also reset the quality tests 
       */
      virtual void reset(bool resetQtests = true);
      
      /**
       *  @brief  Write monitor element to device
       *  
       *  @param  device the device to write to
       */
      virtual core::StatusCode toDevice(xdrstream::IODevice *device) const;
      
      /**
       *  @brief  Read the monitor element from device
       * 
       *  @param  device the device to read from
       */
      virtual core::StatusCode fromDevice(xdrstream::IODevice *device);
     
    protected:
      OnlineElement();
      OnlineElement(TObject *pMonitorObject);
      OnlineElement(TObject *pMonitorObject, TObject *pReferenceObject);
      OnlineElement(const core::PtrHandler<TObject> &monitorObject);
      OnlineElement(const core::PtrHandler<TObject> &monitorObject, const core::PtrHandler<TObject> &referenceObject);
     
      /**
       *  @brief  Set the collector name.
       *          Called by a monitor element collector on collect
       *
       *  @param  colName the collector name
       */
      void setCollectorName(const std::string &colName);
     
      /**
       *  @brief  Set the module name.
       *          Called by the module application on element booking
       *
       *  @param  modName the module name
       */
      void setModuleName(const std::string &modName);

    private:
      /// The run number
      int                           m_runNumber = {0};
      /// The monitor element collector
      std::string                   m_collectorName = {""};
      /// The module name that have produced it
      std::string                   m_moduleName = {""};
      /// The monitor element description
      std::string                   m_description = {""};
    }; 

  }
  
} 

#endif  //  DQM4HEP_ONLINEELEMENT_H
