  /// \file ParameterDirectory.h
/*
 *
 * ParameterDirectory.h header template automatically generated by a class generator
 * Creation date : mer. janv. 25 2017
 *
 * This file is part of DQM4HEP libraries.
 *
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef PARAMETERDIRECTORY_H
#define PARAMETERDIRECTORY_H

#include "dqm4hep/DQM4HEP.h"
#include "dqm4hep/Parameter.h"
#include "dqm4hep/Parameters.h"

namespace dqm4hep {

  namespace core {

    class ParameterHandle;

    /**
     * ParameterDirectory class
     */
    class ParameterDirectory
    {
    public:
      typedef std::map<std::string, ParameterDirectory*>  ParameterDirectoryMap;
      typedef ParameterDirectoryMap::iterator iterator;
      typedef ParameterDirectoryMap::const_iterator const_iterator;

      /**
       * [createToLevelDirectory description]
       */
      static ParameterDirectory *createToLevelDirectory();

      /**
       * Destructor
       */
      ~ParameterDirectory();

      /**
       * Get the directory name
       */
      const std::string &getName() const;

      /**
       *
       */
      std::string getFullName() const;

      /**
       * Create a new subdirectory. If already exists, returns the existing one
       *
       * @param name the name of the directory to create
       */
      ParameterDirectory *mkdir(const std::string &name);

      /**
       *
       */
      bool rmdir(const std::string &name);

      /**
       *
       */
      void ls(bool recursive = false);

      /**
       *
       */
      bool dirExists(const std::string &name) const;

      /**
       *
       */
      const Parameters &getParameters() const;

      /**
       *
       */
      Parameters &getParameters();

      /**
       *
       */
      ParameterHandle createHandle();

      /**
       * [createHandle description]
       * @param  name [description]
       * @return      [description]
       */
      ParameterHandle createHandle(const std::string &name);

      /**
       *
       */
      StringVector getDirectorList() const;

      /**
       *
       */
      iterator begin();

      /**
       *
       */
      iterator end();

      /**
       *
       */
      const_iterator begin() const;

      /**
       *
       */
      const_iterator end() const;

      /**
       *
       */
      iterator find(const std::string &name);

      /**
       *
       */
      const_iterator find(const std::string &name) const;

    private:
      /**
       * Constructor
       */
      ParameterDirectory(const std::string &name, ParameterDirectory *pParent);

      /**
       *
       */
      void ls(bool recursive, unsigned int depth);

    private:
      std::string                         m_name;
      ParameterDirectory                 *m_pParentDirectory;
      Parameters                          m_parameters;
      ParameterDirectoryMap               m_subDirectories;
    };

  }

}

#endif  //  PARAMETERDIRECTORY_H
