/// \file RunControlInterface.h
/*
*
* RunControlInterface.h header template automatically generated by a class generator
* Creation date : mar. janv. 24 2017
*
* This file is part of DQM4HEP libraries.
*
* DQM4HEP is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* based upon these libraries are permitted. Any copy of these libraries
* must include this copyright notice.
*
* DQM4HEP is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
*
* @author Remi ete
* @copyright CNRS , IPNL
*/


#ifndef RUNCONTROLINTERFACE_H
#define RUNCONTROLINTERFACE_H

#include "dqm4hep/Run.h"
#include "dqm4hep/RunControl.h"

namespace dqm4hep {

  namespace core {

    /**
     * RunControlInterface class
     */
    class RunControlInterface
    {
    public:
      /**
       * Constructor
       */
      RunControlInterface();

      /**
       * Destructor
       */
      virtual ~RunControlInterface();

    protected:
      /**
       * Start a new run.
       *
       * @param run the run to start
       * @param password an optional password required to start the new run
       */
      void startNewRun(const Run &run, const std::string &password = "");

      /**
       * End the current run
       *
       * @param password an optional password required to stop the current run
       */
      void endCurrentRun(const std::string &password = "");

    private:
      /**
       * Set the run control for his interface
       *
       * @param pRunControl the run control instance
       */
      void setRunControl(refactor::RunControl *pRunControl);

    private:
      refactor::RunControl          *m_pRunControl;
    };

  }

}

#endif  //  RUNCONTROLINTERFACE_H
